name: Make installer

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  GCC_DOWNLOAD: "https://github.com/brechtsanders/winlibs_mingw/releases/download/10.3.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-10.3.0-mingw-w64-9.0.0-r2.zip"
  GIT_DOWNLOAD: "https://github.com/git-for-windows/git/releases/download/v2.33.1.windows.1/MinGit-2.33.1-64-bit.zip"
  FPM_DOWNLOAD: "https://github.com/fortran-lang/fpm/releases/download/v0.4.0/fpm-0.4.0-windows-x86_64.exe"

jobs:
  make_installer:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MinGW (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          wget
          unzip
          mingw-w64-x86_64-openblas
          
    - name: Fetch Mingw-w64
      shell: msys2 {0}
      run: |
        wget $GCC_DOWNLOAD -O mingw-w64.zip
        unzip mingw-w64.zip

    - name: Fetch Git for Windows
      shell: msys2 {0}
      run: |
        wget $GIT_DOWNLOAD -O MinGit.zip
        unzip MinGit.zip -d MinGit
    
    - name: Fetch FPM
      shell: msys2 {0}
      run: |
        mkdir fpm
        wget $FPM_DOWNLOAD -O fpm/fpm.exe

    - name: Fetch OpenBLAS
      shell: msys2 {0}
      run: |
        mkdir OpenBLAS
        cp /mingw64/bin/libopenblas.dll ./mingw64/bin/
        cp -r /mingw64/include/OpenBLAS ./mingw64/include
        cp -r /mingw64/lib/libopenblas.* ./mingw64/lib/
        mkdir ./mingw64/share/licenses
        cp -r /mingw64/share/licenses/OpenBLAS ./mingw64/share/licenses/

    - name: Generate installer
      run: makensis quickstart-fortran-installer.nsi

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: quickstart-fortran-installer
        path: quickstart-fortran-installer.exe
    
    - name: Create/Update tag
      if: ${{ github.event_name != 'release' }}
      run: |
        git tag --force 'Latest' ${{ github.sha }}
        git push --tags --force

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: quickstart-fortran-installer.exe
        tag: ${{ github.event_name == 'release' && github.ref || 'Latest'}}
        overwrite: true