name: Make installer

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  GCC_DOWNLOAD: "https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-9.0.0-msvcrt-r6/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r6.zip"
  GIT_DOWNLOAD: "https://github.com/git-for-windows/git/releases/download/v2.35.2.windows.1/MinGit-2.35.2-64-bit.zip"
  FPM_DOWNLOAD: "https://github.com/fortran-lang/fpm/releases/download/v0.5.0/fpm-0.5.0-windows-x86_64.exe"
  ENVAR_DOWNLOAD: "https://github.com/GsNSIS/EnVar/releases/download/v0.3.1/EnVar-Plugin.zip"

jobs:
  make_installer:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MinGW (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          wget
          unzip
          mingw-w64-x86_64-openblas
          
    - name: Fetch Mingw-w64
      shell: msys2 {0}
      run: |
        wget $GCC_DOWNLOAD -O mingw-w64.zip
        unzip mingw-w64.zip

    - name: Add Mingw-w64 to path to build fpm
      run: echo "$pwd\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Checkout fpm code
      uses: actions/checkout@v2
      with:
        repository: fortran-lang/fpm
        ref: v0.5.0
        path: fpm-src
    
    - name: Install fpm for bootstrapping
      uses: fortran-lang/setup-fpm@v3
      with:
        fpm-version: 'v0.5.0'

    - name: Build fpm from source with OpenMP
      run: |
        mkdir fpm
        gfortran --version
        fpm run -C fpm-src --profile release --flag "-fopenmp --static" --runner copy -- ..\fpm\

    - name: Remove fpm src
      shell: msys2 {0}
      run: rm -rf fpm-src

    - name: Fetch Git for Windows
      shell: msys2 {0}
      run: |
        wget $GIT_DOWNLOAD -O MinGit.zip
        unzip MinGit.zip -d MinGit

    - name: Fetch EnVar Plugin for NSIS
      shell: msys2 {0}
      run: |
        wget $ENVAR_DOWNLOAD -O EnVar-Plugin.zip
        mkdir -p nsis-plugins/EnVar_plugin
        unzip EnVar-Plugin.zip -d nsis-plugins/EnVar_plugin

    - name: Fetch OpenBLAS
      shell: msys2 {0}
      run: |
        mkdir OpenBLAS
        cp /mingw64/bin/libopenblas.dll ./mingw64/bin/
        cp -r /mingw64/include/OpenBLAS ./mingw64/include
        cp -r /mingw64/lib/libopenblas.* ./mingw64/lib/
        mkdir ./mingw64/share/licenses
        cp -r /mingw64/share/licenses/OpenBLAS ./mingw64/share/licenses/

    - name: Generate installer
      run: makensis quickstart-fortran-installer.nsi

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: quickstart-fortran-installer
        path: quickstart-fortran-installer.exe

    - name: Upload to release
      if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: quickstart-fortran-installer.exe
        tag: ${{ github.ref }}
        overwrite: true
